### ISSUE TITLE
remove directory in sampleoutput

### ISSUE THREAD

**Issue by probinso** [GaloisInc/ppaml-cp4#1]
I believe the 'empty' and 'qmark' directories and contents no longer serve a purpose. 

Lets delete them.

**Comment by slater-ppaml** [comment]
Sounds good. Can you go ahead and delete them?

Thanks,
Michael

**Comment by slater-ppaml** [comment]
I went ahead and deleted them.

Michael

**Comment by slater-ppaml** [comment]
Issue is being closed.
