### ISSUE TITLE
Updated posterior for CP4.2?

### ISSUE THREAD

**Issue by axch** [GaloisInc/ppaml-cp4#14]
I notice that the disease prior for the QMR problem has changed
substantially from the Dec 2014 round.  Could you please update the
full posterior,
problem-2-tvd-against-ground/problem-2-case?-posterior-disease-config-prob.csv,
for purposes of computing total variation distance?

I assume the max a-posteriori solutions in problem-2-solution-map.csv
are still the same.

Might also want to update the marginals in
problem-2-solution-marginal.csv, because I assume they would have
changed; but it's not very important to us because we are not using
them for anything currently.

**Comment by ssorower** [comment]
Hi Alexey,
Thanks for pointing this out. I have updated the marginal and the posterior CSVs. And you're right - max-a-posteriori solutions are still the same.

**Comment by axch** [comment]
Thanks!
